apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: almalinux
    image: almalinux
    command: ["/bin/sh", "-c", "while true; do echo Hello from AlmaLinux; sleep 10; done"]