apiVersion: v1
kind: Namespace
metadata:
  name: roboshop 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    app: myapp
spec:
  containers: 
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"